name: Update GitHub Profile README

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches:
      - main
      - feature/gitgotchi-integration

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0


      - name: Generate README.md
        uses: night-slayer18/profile-readme-stats@master
        with:
          token: ${{ secrets.USER_TOKEN }}
          includeForks: true

      - name: GitGotchi Profile Pet
        uses: night-slayer18/gitgotchi@v1
        with:
          token: ${{ secrets.USER_TOKEN }}
          template_file: 'README.md'
          theme: 'ocean'

      - name: Update README.md
        run: |
          if [[ "$(git status --porcelain)" != "" ]]; then
            git config user.name 'night-slayer18'
            git config user.email 'samanuaia257@gmail.com'
            git add .
            git commit -m "Update README"
            git push
          fi
